name: Build

on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - main

jobs:
  build-plugin:
    name: Building plugin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
