name: Build

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  pre-release:
    name: Pre-release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.sha }}
          files: |
            LICENSE
            nexus-pac4j-plugin/target/*.jar
